# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - WP_VERSION=master BP_VERSION=master
    - WP_VERSION=4.2 BP_VERSION=master
    - WP_VERSION=4.2 BP_VERSION=2.3
    - WP_VERSION=4.1 BP_VERSION=master
    - WP_VERSION=4.1 BP_VERSION=2.3
    - WP_VERSION=4.0 BP_VERSION=master
    - WP_VERSION=4.0 BP_VERSION=2.3
    - WP_VERSION=3.9 BP_VERSION=master
    - WP_VERSION=3.9 BP_VERSION=2.3
    - WP_VERSION=3.8 BP_VERSION=master
    - WP_VERSION=3.8 BP_VERSION=2.3

matrix:
  fast_finish: true
  include:
    - php: 5.2
      env: WP_VERSION=master BP_VERSION=master
    - php: 7.0
      env: WP_VERSION=master BP_VERSION=master
    - php: hhvm
      env: WP_VERSION=master BP_VERSION=master
  allow_failures:
    - php: 7.0
    - php: hhvm

# Clones WordPress and configures our testing environment.
before_script:
    - bash bin/install-wp-tests-travis.sh wordpress_test root '' localhost $WP_VERSION $BP_VERSION

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
